'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Plus, X } from 'lucide-react'
import { BrandColor } from '@/types/brand'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { TAILWIND_COLORS, TailwindColorName } from '@/lib/tailwind-colors'
import { ColorPickerInput } from '@/components/color-picker-input'

interface BrandColorManagerProps {
  colors: BrandColor[]
  onColorsChange: (colors: BrandColor[]) => void
}

export function BrandColorManager({ colors, onColorsChange }: BrandColorManagerProps) {
  const [isAddingColor, setIsAddingColor] = useState(false)
  const [newColorType, setNewColorType] = useState<'tailwind' | 'custom'>('tailwind')
  const [selectedColorName, setSelectedColorName] = useState<TailwindColorName>('blue')
  const [customColorValue, setCustomColorValue] = useState('#3b82f6')

  const canAddMore = colors.length < 3

  const colorNames = Object.keys(TAILWIND_COLORS) as TailwindColorName[]

  const generateColorName = (type: 'tailwind' | 'custom', colorName?: string): string => {
    if (type === 'tailwind' && colorName) {
      return colorName.charAt(0).toUpperCase() + colorName.slice(1)
    } else {
      const customCount = colors.filter(c => !c.isTailwindColor).length
      return `Custom ${customCount + 1}`
    }
  }

  const handleAddColor = () => {
    const autoGeneratedName = generateColorName(
      newColorType,
      newColorType === 'tailwind' ? selectedColorName : undefined
    )

    const newColor: BrandColor = {
      id: Date.now().toString(),
      name: autoGeneratedName,
      value: newColorType === 'tailwind' ? selectedColorName : customColorValue,
      isTailwindColor: newColorType === 'tailwind',
    }

    onColorsChange([...colors, newColor])
    setIsAddingColor(false)
    setCustomColorValue('#3b82f6')
    setSelectedColorName('blue')
  }

  const handleRemoveColor = (id: string) => {
    onColorsChange(colors.filter((c) => c.id !== id))
  }

  const handleUpdateColor = (id: string, updates: Partial<BrandColor>) => {
    const updatedColors = colors.map((c) => {
      if (c.id !== id) return c
      
      const updated = { ...c, ...updates }
      
      if (updated.isTailwindColor && updates.value) {
        updated.name = generateColorName('tailwind', updates.value)
      }
      
      return updated
    })
    
    onColorsChange(updatedColors)
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <Label className="text-sm font-semibold">Brand Colors ({colors.length}/3)</Label>
        {canAddMore && !isAddingColor && (
          <Button
            size="sm"
            variant="outline"
            onClick={() => setIsAddingColor(true)}
          >
            <Plus className="h-4 w-4 mr-1" />
            Add Color
          </Button>
        )}
      </div>

      {/* Existing Colors */}
      <div className="space-y-3">
        {colors.map((color) => {
          const displayColorValue = color.isTailwindColor 
            ? TAILWIND_COLORS[color.value as TailwindColorName]['500']
            : color.value
          
          return (
            <div key={color.id} className="flex items-start gap-2 p-3 rounded-lg border border-border bg-card">
              <div className="flex-1 space-y-3">
                <div className="flex items-center gap-2">
                  <div
                    className="w-10 h-10 rounded border border-border flex-shrink-0"
                    style={{ backgroundColor: displayColorValue }}
                  />
                  <div className="px-3 py-2 bg-muted rounded-md flex-1">
                    <p className="text-sm font-medium">{color.name}</p>
                  </div>
                </div>
                
                {color.isTailwindColor ? (
                  <Select
                    value={color.value}
                    onValueChange={(colorName: TailwindColorName) => 
                      handleUpdateColor(color.id, { value: colorName })
                    }
                  >
                    <SelectTrigger className="h-8">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="max-h-60">
                      {colorNames.map((name) => (
                        <SelectItem key={name} value={name}>
                          <div className="flex items-center gap-2">
                            <div
                              className="w-4 h-4 rounded border border-border"
                              style={{ backgroundColor: TAILWIND_COLORS[name]['500'] }}
                            />
                            {name}
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                ) : (
                  <ColorPickerInput
                    label=""
                    value={color.value}
                    onChange={(value) => handleUpdateColor(color.id, { value })}
                  />
                )}
              </div>
              <Button
                size="icon"
                variant="ghost"
                onClick={() => handleRemoveColor(color.id)}
                className="h-8 w-8 text-muted-foreground hover:text-destructive"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          )
        })}
      </div>

      {/* Add New Color Form */}
      {isAddingColor && (
        <div className="p-4 rounded-lg border border-border bg-card space-y-3">
          
          <div className="space-y-2">
            <Label>Color Type</Label>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant={newColorType === 'tailwind' ? 'default' : 'outline'}
                onClick={() => setNewColorType('tailwind')}
                className="flex-1"
              >
                Tailwind Color
              </Button>
              <Button
                size="sm"
                variant={newColorType === 'custom' ? 'default' : 'outline'}
                onClick={() => setNewColorType('custom')}
                className="flex-1"
              >
                Custom Color
              </Button>
            </div>
          </div>

          {newColorType === 'tailwind' ? (
            <>
              <div className="space-y-2">
                <Label>Select Color</Label>
                <Select value={selectedColorName} onValueChange={(value: TailwindColorName) => setSelectedColorName(value)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="max-h-60">
                    {colorNames.map((name) => (
                      <SelectItem key={name} value={name}>
                        <div className="flex items-center gap-2">
                          <div
                            className="w-4 h-4 rounded border border-border"
                            style={{ backgroundColor: TAILWIND_COLORS[name]['500'] }}
                          />
                          {name}
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <div className="grid grid-cols-11 gap-1 mt-2">
                  {(['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'] as const).map((shade) => (
                    <div
                      key={shade}
                      className="aspect-square rounded border border-border/50"
                      style={{ backgroundColor: TAILWIND_COLORS[selectedColorName][shade] }}
                      title={`${selectedColorName}-${shade}`}
                    />
                  ))}
                </div>
                <p className="text-xs text-muted-foreground">
                  All shades will be available for use in your design
                </p>
              </div>
            </>
          ) : (
            <ColorPickerInput
              label="Custom Color"
              value={customColorValue}
              onChange={setCustomColorValue}
            />
          )}

          <div className="flex gap-2">
            <Button onClick={handleAddColor} className="flex-1">
              Add
            </Button>
            <Button variant="outline" onClick={() => setIsAddingColor(false)} className="flex-1">
              Cancel
            </Button>
          </div>
        </div>
      )}
    </div>
  )
}
